### ISSUE TITLE
something broke in 0.6.2

### ISSUE THREAD

**Issue by mreinstein** [jscrambler/node-jscrambler#28]
getting this error now:

```bash
/Users/michaelreinstein/wwwroot/level-editor/node_modules/jscrambler/bin/jscrambler:52
  commander.accessKey = commander.accessKey || config.keys.accessKey;
                                                          ^
TypeError: Cannot read property 'accessKey' of undefined
    at Object.<anonymous> (/Users/michaelreinstein/wwwroot/level-editor/node_modules/jscrambler/bin/jscrambler:52:59)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

I'm using the config file feature. It has something to do with this.

**Comment by mreinstein** [comment]
I'm not getting the error any more, but now I'm experiencing other problems. I'll open a separate ticket.
