### ISSUE TITLE
jScrambler.Client is not a function

### ISSUE THREAD

**Issue by Wambosa** [jscrambler/node-jscrambler#38]
Taking the example exactly from the readme.md

1. copy the example and create test.js
2. npm install fs-extra
3. npm install jscrambler
4. > node test.js

expect: auth error or success given that the file args and keys are good.
actual: 
TypeError: jScrambler.Client is not a function
    at Object.<anonymous> (W:\work\test.js:4:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by magalhas** [comment]
When running `npm install jscrambler` you are installing the latest version of the client which is not the one on this repository. To use the one on this repository you need to `npm install jscrambler@^0`.

There was a typo in the README that I've fixed meanwhile.
